// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "rucking_api.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface nullRuckingApiPigeonCodecReader : FlutterStandardReader
@end
@implementation nullRuckingApiPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullRuckingApiPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullRuckingApiPigeonCodecWriter
- (void)writeValue:(id)value {
  {
    [super writeValue:value];
  }
}
@end

@interface nullRuckingApiPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullRuckingApiPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullRuckingApiPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullRuckingApiPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetRuckingApiCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullRuckingApiPigeonCodecReaderWriter *readerWriter = [[nullRuckingApiPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpRuckingApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<RuckingApi> *api) {
  SetUpRuckingApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpRuckingApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<RuckingApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  /// Start a new session from the watch
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.RuckingApi.startSessionFromWatch", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetRuckingApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startSessionFromWatchRuckWeight:completion:)], @"RuckingApi api (%@) doesn't respond to @selector(startSessionFromWatchRuckWeight:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        double arg_ruckWeight = [GetNullableObjectAtIndex(args, 0) doubleValue];
        [api startSessionFromWatchRuckWeight:arg_ruckWeight completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Pause an active session from the watch
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.RuckingApi.pauseSessionFromWatch", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetRuckingApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pauseSessionFromWatchWithCompletion:)], @"RuckingApi api (%@) doesn't respond to @selector(pauseSessionFromWatchWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api pauseSessionFromWatchWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Resume a paused session from the watch
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.RuckingApi.resumeSessionFromWatch", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetRuckingApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(resumeSessionFromWatchWithCompletion:)], @"RuckingApi api (%@) doesn't respond to @selector(resumeSessionFromWatchWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api resumeSessionFromWatchWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// End the current session from the watch
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.RuckingApi.endSessionFromWatch", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetRuckingApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(endSessionFromWatchDuration:distance:calories:completion:)], @"RuckingApi api (%@) doesn't respond to @selector(endSessionFromWatchDuration:distance:calories:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_duration = [GetNullableObjectAtIndex(args, 0) integerValue];
        double arg_distance = [GetNullableObjectAtIndex(args, 1) doubleValue];
        double arg_calories = [GetNullableObjectAtIndex(args, 2) doubleValue];
        [api endSessionFromWatchDuration:arg_duration distance:arg_distance calories:arg_calories completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Update heart rate from the watch
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.RuckingApi.updateHeartRateFromWatch", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetRuckingApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(updateHeartRateFromWatchHeartRate:completion:)], @"RuckingApi api (%@) doesn't respond to @selector(updateHeartRateFromWatchHeartRate:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        double arg_heartRate = [GetNullableObjectAtIndex(args, 0) doubleValue];
        [api updateHeartRateFromWatchHeartRate:arg_heartRate completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FlutterRuckingApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation FlutterRuckingApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)updateSessionOnWatchDistance:(double)arg_distance duration:(double)arg_duration pace:(double)arg_pace isPaused:(BOOL)arg_isPaused completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.FlutterRuckingApi.updateSessionOnWatch", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetRuckingApiCodec()];
  [channel sendMessage:@[@(arg_distance), @(arg_duration), @(arg_pace), @(arg_isPaused)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)startSessionOnWatchRuckWeight:(double)arg_ruckWeight completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.FlutterRuckingApi.startSessionOnWatch", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetRuckingApiCodec()];
  [channel sendMessage:@[@(arg_ruckWeight)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)pauseSessionOnWatchWithCompletion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.FlutterRuckingApi.pauseSessionOnWatch", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetRuckingApiCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)resumeSessionOnWatchWithCompletion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.FlutterRuckingApi.resumeSessionOnWatch", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetRuckingApiCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)endSessionOnWatchWithCompletion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.rucking_app.FlutterRuckingApi.endSessionOnWatch", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetRuckingApiCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

