// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class RuckingApiPigeonCodecReader: FlutterStandardReader {
}

private class RuckingApiPigeonCodecWriter: FlutterStandardWriter {
}

private class RuckingApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RuckingApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RuckingApiPigeonCodecWriter(data: data)
  }
}

class RuckingApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RuckingApiPigeonCodec(readerWriter: RuckingApiPigeonCodecReaderWriter())
}


/// Messages from Watch to Flutter
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RuckingApi {
  /// Start a new session from the watch
  func startSessionFromWatch(ruckWeight: Double, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Pause an active session from the watch
  func pauseSessionFromWatch(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Resume a paused session from the watch
  func resumeSessionFromWatch(completion: @escaping (Result<Bool, Error>) -> Void)
  /// End the current session from the watch
  func endSessionFromWatch(duration: Int64, distance: Double, calories: Double, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Update heart rate from the watch
  func updateHeartRateFromWatch(heartRate: Double, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RuckingApiSetup {
  static var codec: FlutterStandardMessageCodec { RuckingApiPigeonCodec.shared }
  /// Sets up an instance of `RuckingApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RuckingApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Start a new session from the watch
    let startSessionFromWatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rucking_app.RuckingApi.startSessionFromWatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSessionFromWatchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ruckWeightArg = args[0] as! Double
        api.startSessionFromWatch(ruckWeight: ruckWeightArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startSessionFromWatchChannel.setMessageHandler(nil)
    }
    /// Pause an active session from the watch
    let pauseSessionFromWatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rucking_app.RuckingApi.pauseSessionFromWatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseSessionFromWatchChannel.setMessageHandler { _, reply in
        api.pauseSessionFromWatch { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pauseSessionFromWatchChannel.setMessageHandler(nil)
    }
    /// Resume a paused session from the watch
    let resumeSessionFromWatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rucking_app.RuckingApi.resumeSessionFromWatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeSessionFromWatchChannel.setMessageHandler { _, reply in
        api.resumeSessionFromWatch { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resumeSessionFromWatchChannel.setMessageHandler(nil)
    }
    /// End the current session from the watch
    let endSessionFromWatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rucking_app.RuckingApi.endSessionFromWatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionFromWatchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let durationArg = args[0] as! Int64
        let distanceArg = args[1] as! Double
        let caloriesArg = args[2] as! Double
        api.endSessionFromWatch(duration: durationArg, distance: distanceArg, calories: caloriesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      endSessionFromWatchChannel.setMessageHandler(nil)
    }
    /// Update heart rate from the watch
    let updateHeartRateFromWatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rucking_app.RuckingApi.updateHeartRateFromWatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateHeartRateFromWatchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let heartRateArg = args[0] as! Double
        api.updateHeartRateFromWatch(heartRate: heartRateArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateHeartRateFromWatchChannel.setMessageHandler(nil)
    }
  }
}
/// Messages from Flutter to Watch
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterRuckingApiProtocol {
  /// Update session metrics on the watch
  func updateSessionOnWatch(distance distanceArg: Double, duration durationArg: Double, pace paceArg: Double, isPaused isPausedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Start a session on the watch
  func startSessionOnWatch(ruckWeight ruckWeightArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Pause a session on the watch
  func pauseSessionOnWatch(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Resume a session on the watch
  func resumeSessionOnWatch(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// End a session on the watch
  func endSessionOnWatch(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FlutterRuckingApi: FlutterRuckingApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: RuckingApiPigeonCodec {
    return RuckingApiPigeonCodec.shared
  }
  /// Update session metrics on the watch
  func updateSessionOnWatch(distance distanceArg: Double, duration durationArg: Double, pace paceArg: Double, isPaused isPausedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rucking_app.FlutterRuckingApi.updateSessionOnWatch\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([distanceArg, durationArg, paceArg, isPausedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Start a session on the watch
  func startSessionOnWatch(ruckWeight ruckWeightArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rucking_app.FlutterRuckingApi.startSessionOnWatch\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([ruckWeightArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Pause a session on the watch
  func pauseSessionOnWatch(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rucking_app.FlutterRuckingApi.pauseSessionOnWatch\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Resume a session on the watch
  func resumeSessionOnWatch(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rucking_app.FlutterRuckingApi.resumeSessionOnWatch\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// End a session on the watch
  func endSessionOnWatch(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rucking_app.FlutterRuckingApi.endSessionOnWatch\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
